import Head from 'next/head'
import React from "react";
import Image from 'next/image'
import Page from '../components/Page'
import Comments from '../components/Comments'
import { db } from '../utils/firebase'
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore'
import { useAuthState } from "react-firebase-hooks/auth";
import { myAuth } from "../utils/firebase";
import Link from 'next/link';

export default function Home() {
  const [comments, setComments] = React.useState([])
  const [user, loading] = useAuthState(myAuth);

  //Getting the comments from cloud firestore
  const getComments = async () => {
    const collectionRef = collection(db, 'posts')
    const data = query(collectionRef, orderBy('timestamp', 'desc'))
    const unsubscribe = onSnapshot(data, (snapshot) => {
      setComments(snapshot.docs.map((item) => ({...item.data(), id: item.id})))
    })
    return unsubscribe
  }

  React.useEffect(() => {
    getComments()
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-5 font-medium'>
        <h2 className="text-2xl text-center ">{user ? "Read comments from other accounts" : "Log In To See Posts"}</h2>
        {comments.map(item => ( 
          <Comments {...item} key={item.id}>
            <Link href={{ pathname: `/${item.id}`, query: {...item} }} legacyBehavior>
              <button>{item.comments?.length > 0 ? item.comments?.length : 0} Comments</button>
            </Link>
          </Comments>
        ))}
      </div>

      <footer >
        
      </footer>
    </div>
  )
}
